src/home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
  path("", views.index, name="index"),
  path("about/", views.about, name="about"),
  path("donate/", views.donate, name="donate"),
  path("volunteer/", views.volunteer, name="volunteer"),
  path("privacy/", views.privacy, name="privacy"),
  path("questions-and-answers/",
       views.questions_and_answers,
       name="questions-and-answers"),
  path("contact/", views.contact, name="contact"),
  path("financials/", views.financials, name="financials"),
]

src/triallocator/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("home.urls")),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

handler404 = "theme.views.page_not_found_view"

src/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

class UserManager(BaseUserManager):
  use_in_migrations = True

  def _create_user(self, email, password, **extra_fields):
    if not email:
      raise ValueError(_('Email must be provided'))
    email = self.normalize_email(email)
    user = self.model(email=email, **extra_fields)
    user.set_password(password)
    user.save()
    return user

  def create_user(self, email, password=None, **extra_fields):
    extra_fields.setdefault('is_staff', False)
    extra_fields.setdefault('is_superuser', False)
    return self._create_user(email, password, **extra_fields)

  def create_superuser(self, email, password, **extra_fields):
    extra_fields.setdefault('is_staff', True)
    extra_fields.setdefault('is_superuser', True)

    if extra_fields.get('is_staff') is not True:
      raise ValueError('Superuser must have is_staff=True.')
    if extra_fields.get('is_superuser') is not True:
      raise ValueError('Superuser must have is_superuser=True.')

    return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
  username = None
  email = models.EmailField(_('email address'), unique=True)

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = []

  objects = UserManager()

  def __str__(self):
    return self.email

src/home/models.py
from django.db import models

# Create your models here.

src/trials/models.py
from django.db import models

class TrialStatus(models.TextChoices):
  ACTIVE_NOT_RECRUITING = "Active, not recruiting"
  COMPLETED = "Completed"
  ENROLLING_BY_INVITATION = "Enrolling by invitation"
  NOT_YET_RECRUITING = "Not yet recruiting"
  RECRUITING = "Recruiting"
  SUSPENDED = "Suspended"
  TERMINATED = "Terminated"
  WITHDRAWN = "Withdrawn"
  AVAILABLE = "Available"
  NO_LONGER_AVAILABLE = "No longer available"
  TEMPORARILY_NOT_AVAILABLE = "Temporarily not available"
  APPROVED_FOR_MARKETING = "Approved for marketing"
  WITHHELD = "Withheld"
  UNKNOWN = "Unknown status"

class ClinicalTrial(models.Model):
  class AgencyClass(models.TextChoices):
    NIH = "NIH"
    FED = "FED"
    OTHER_GOV = "Other Gov"
    INDIV = "Indiv"
    INDUSTRY = "Industry"
    NETWORK = "Network"
    AMBIG = "Ambiguous"
    OTHER = "Other"
    UNKNOWN = "Unknown"

  class Sex(models.TextChoices):
    FEMALE = "F"
    MALE = "M"
    ALL = "All"

  class ResponsibleParty(models.TextChoices):
    SPONSOR = "Sponsor"
    PRINCIPAL_INVESTIGATOR = "Principal Investigator"
    SPONSOR_INVESTIGATOR = "Sponsor-Investigator"

  class StudyType(models.TextChoices):
    EXPANDED_ACCESS = "Expanded Access"
    INTERVENTIONAL = "Interventional"
    OBSERVATIONAL = "Observational"

  class Phase(models.TextChoices):
    NOT_APPLICABLE = "NA"
    EARLY_PHASE_1 = "Early phase 1"
    PHASE_1 = "1"
    PHASE_2 = "2"
    PHASE_3 = "3"
    PHASE_4 = "4"

  # This first section is just data I can get from clinicaltrials.gov
  # protocolSection.identificationModule.nctId
  nct_id = models.CharField(max_length=11)

  # protocolSection.identificationModule.briefTitle
  brief_title = models.CharField()

  # protocolSection.identificationModule.officialTitle
  official_title = models.CharField()

  # protocolSection.identificationModule.organization.fullName
  organization_name = models.CharField()

  # protocolSection.identificationModule.organization.class
  organization_type = models.CharField(choices=AgencyClass)

  # protocolSection.statusModule.statusVerifiedDate
  record_verification_date = models.DateField()

  # protocolSection.statusModule.overallStatus
  overall_status = models.CharField(choices=TrialStatus)

  # protocolSection.statusModule.startDateStruct.date
  start_date = models.DateField()

  # protocolSection.statusModule.studyFirstPostDateStruct.date
  date_posted = models.DateField()

  # protocolSection.sponsorCollaboratorsModule.responsibleParty.type
  responsible_party = models.CharField(choices=ResponsibleParty)

  # protocolSection.eligibilityModule.eligibilityCriteria
  eligibility_criteria = models.TextField()

  # protocolSection.eligibilityModule.sex
  eligible_sex = models.CharField(choices=Sex)

  # protocolSection.eligibilityModule.minimumAge
  min_age = models.CharField()

  # protocolSection.eligibilityModule.maximumAge
  max_age = models.CharField()

  # protocolSection.eligibilityModule.studyPopulation
  study_population = models.TextField()


  # TODO: add description module
  # TODO: add conditions module
  # TODO: add design module
  # TODO: add arms intervention module

  def __str__(self):
    return f"{self.nct_id}: {self.brief_title}"

  class PrimaryPurpose(models.TextChoices):
    TREATMENT = "Treatment"
    PREVENTION = "Prevention"
    DIAGNOSTIC = "Diagnostic"
    ECT = "Educational/Counseling/Training"
    SUPPORTIVE_CARE = "Supportive care"
    SCREENING = "Screening"
    HEALTH_SERVICES_RESEARCH = "Health services research"
    BASIC_SCIENCE = "Basic science"
    DEVICE_FEASIBILITY = "Device feasibility"
    OTHER = "Other"

  class ArmGroupType(models.TextChoices):
    EXPERIMENTAL = "Experimental"
    ACTIVE_COMPARATOR = "Active comparator"
    PLACEBO_COMPARATOR = "Placebo comparator"
    SHAM_COMPARATOR = "Sham comparator"
    NO_INTERVENTION = "No intervention"
    OTHER = "Other"

  class InterventionType(models.TextChoices):
    BEHAVIORAL = "Behavioral"
    BIOLOGICAL = "Biological"
    COMBINATION_PRODUCT = "Combination Product"
    DEVICE = "Device"
    DIAGNOSTIC_TEST = "Diagnostic Test"
    DIETARY_SUPPLEMENT = "Dietary Supplement"
    DRUG = "Drug"
    GENETIC = "Genetic"
    PROCEDURE = "Procedure"
    RADIATION = "Radiation"
    OTHER = "Other"


# TODO: finish
class Location(models.Model):
  trials = models.ManyToManyField(ClinicalTrial)
  status = models.CharField(choices=TrialStatus)

# TODO: finish
class Contact(models.Model):
  trials = models.ManyToManyField(ClinicalTrial)

# TODO finish
class Collaborator(models.Model):
  trials = models.ManyToManyField(ClinicalTrial)

# TODO finish
# each trial has one or more targeted outcomes
class Outcome(models.Model):
  trials = models.ManyToManyField(ClinicalTrial)

src/accounts/views.py
from django.shortcuts import render

# Create your views here.

src/home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

def index(request):
  template = loader.get_template("home/index.html")
  context = { "home_page_active": True, }
  return HttpResponse(template.render(context, request))

def about(request):
  template = loader.get_template("home/about.html")
  context = { "about_page_active": True, }
  return HttpResponse(template.render(context, request))

def donate(request):
  template = loader.get_template("home/donate.html")
  context = { "donate_page_active": True, }
  return HttpResponse(template.render(context, request))

def volunteer(request):
  template = loader.get_template("home/volunteer.html")
  context = { "volunteer_page_active": True, }
  return HttpResponse(template.render(context, request))

def questions_and_answers(request):
  template = loader.get_template("home/q-and-a.html")
  context = { "q_and_a_page_active": True, }
  return HttpResponse(template.render(context, request))

def privacy(request):
  return HttpResponse("Hello, world. You're at the triallocator.org privacy page.")

def contact(request):
  template = loader.get_template("home/contact.html")
  context = {}
  return HttpResponse(template.render(context, request))

def financials(request):
  template = loader.get_template("home/financials.html")
  context = {}
  return HttpResponse(template.render(context, request))

src/theme/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

def page_not_found_view(request, exception):
  template = loader.get_template("theme/404.html")
  context = {}
  return HttpResponse(template.render(context, request))

src/home/templates/home/about.html
{% extends "theme/base.html" %}

{% block title %}Trial Locator{% endblock %}
{% block header_title %}About{% endblock %}
{% block main %}
<main>
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-slate-700">
    <div class="max-w-prose">
      <p class="mt-6">Trial Locator was founded with a singular mission: to make finding and enrolling in life-changing clinical
      trials as easy as possible. Medicine, particularly oncology, is undergoing a revolution. Once untreatable diseases are
      becoming treatable, and in some cases curable, but for many people the most promising treatments for their condition are
      unavailable to them because those treatments are still going through clinical trials.</p>

      <p class="mt-4">The drug approval process is well intentioned and run by people who care about patient safety and wellbeing.
      Unfortunately, for many people the process takes too long and they die or become too sick for treatment before the drugs
      that could help them become available. By making it easier for people to find what trials they are eligible for and discover
      which of those trials are the most promising, and by reducing the friction involved in enrolling in trials, we can help more
      people live longer, healthier lives than they otherwise would.</p>

      <p class='mt-4'>We are run as a nonprofit and are in the process of converting from a C corp to a 501(c)(3) nonprofit. Our
      financial data can be found <a href="{% url 'home:financials' %}" class="text-indigo-600 hover:text-indigo-500">here</a>.
      If you would like to help us serve more people, more effectively you can <a href="{% url 'home:donate' %}"
      class="text-indigo-600 hover:text-indigo-500">donate</a> or learn <a href="{% url 'home:volunteer' %}"
      class="text-indigo-600 hover:text-indigo-500">how to volunteer</a>.</p>
  </div>
  </div>
</main>
{% endblock %}

src/home/templates/home/contact.html
{% extends "theme/base.html" %}

{% block title %}Trial Locator{% endblock %}
{% block header %}{% endblock %}

src/home/templates/home/donate.html
{% extends "theme/base.html" %}

{% block title %}Trial Locator{% endblock %}
{% block header %}{% endblock %}

src/home/templates/home/financials.html
{% extends "theme/base.html" %}

{% block title %}Trial Locator{% endblock %}
{% block header_title %}Financials{% endblock %}
{% block main %}
<main>
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-slate-700">
    <div class="max-w-prose">
      <p class="mt-6">Our first quarter financials will be published after Q1 2024.</p>
  </div>
  </div>
</main>
{% endblock %}

src/home/templates/home/index.html
{% extends "theme/base.html" %}

{% block title %}Trial Locator{% endblock %}

src/home/templates/home/q-and-a.html
{% extends "theme/base.html" %}

{% block title %}Trial Locator{% endblock %}
{% block header %}{% endblock %}

src/home/templates/home/volunteer.html
{% extends "theme/base.html" %}

{% block title %}Trial Locator{% endblock %}
{% block header %}{% endblock %}

src/theme/templates/theme/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="h-full">
	<head>
    <title>{% block title %}Django Tailwind{% endblock %}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_preload_css %}
		{% tailwind_css %}
		<script defer src="{% static 'js/dist/htmx.min.js' %}"></script>
		<script defer src="{% static 'js/dist/alpinejs.min.js' %}"></script>
	</head>
	<body hx-boost="true" class="flex flex-col h-screen min-h-screen bg-gray-50 font-serif leading-normal tracking-normal">
{% block content %}
<div class="flex-1">
  <nav class="border-b border-gray-200 bg-white" x-data="{ main_menu_open: false }">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 justify-between">
        <div class="flex">
          <div class="flex flex-shrink-0 items-center">
            <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Trial Locator">
            <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Trial Locator">
          </div>
          <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
          	{% if home_page_active %}
          		<a href="{% url 'home:index' %}" class="border-indigo-500 text-gray-900 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium" aria-current="page">Trial Locator</a>
            {% else %}
            	<a href="{% url 'home:index' %}" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium">Trial Locator</a>
            {% endif %}
            {% if about_page_active %}
            	<a href="{% url 'home:about' %}" class="border-indigo-500 text-gray-900 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium" aria-current="page">About</a>
            {% else %}
            	<a href="{% url 'home:about' %}" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium">About</a>
            {% endif %}
            {% if volunteer_page_active %}
              <a href="{% url 'home:volunteer' %}" class="border-indigo-500 text-gray-900 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium" aria-current="page">Volunteer</a>
            {% else %}
            	<a href="{% url 'home:volunteer' %}" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium">Volunteer</a>
            {% endif %}
            {% if donate_page_active %}
            	<a href="{% url 'home:donate' %}" class="border-indigo-500 text-gray-900 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium" aria-current="page">Donate</a>
            {% else %}
            	<a href="{% url 'home:donate' %}" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium">Donate</a>
            {% endif %}
            {% if q_and_a_page_active %}
            	<a href="{% url 'home:questions-and-answers' %}" class="border-indigo-500 text-gray-900 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium" aria-current="page">Q&A</a>
            {% else %}
            	<a href="{% url 'home:questions-and-answers' %}" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium">Q&A</a>
            {% endif %}
          </div>
        </div>
        <div class="-mr-2 flex items-center sm:hidden">
          <!-- Mobile menu button -->
          <button type="button" class="relative inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" aria-controls="mobile-menu" aria-expanded="false" @click="main_menu_open = !main_menu_open">
            <span class="absolute -inset-0.5"></span>
            <span class="sr-only">Open main menu</span>
            <svg x-show="!main_menu_open" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
            <svg x-show="main_menu_open" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="sm:hidden" x-show="main_menu_open">
      <div class="space-y-1 pb-3 pt-2">
      	{% if home_page_active %}
        	<a href="{% url 'home:index' %}" class="border-indigo-500 bg-indigo-50 text-indigo-700 block border-l-4 py-2 pl-3 pr-4 text-base font-medium" aria-current="page">Trial Locator</a>
        {% else %}
        	<a href="{% url 'home:index' %}" class="border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium">Trial Locator</a>
        {% endif %}
        {% if about_page_active %}
        	<a href="{% url 'home:about' %}" class="border-indigo-500 bg-indigo-50 text-indigo-700 block border-l-4 py-2 pl-3 pr-4 text-base font-medium" aria-current="page">About</a>
        {% else %}
        	<a href="{% url 'home:about' %}" class="border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium">About</a>
        {% endif %}
        {% if volunteer_page_active %}
        	<a href="{% url 'home:volunteer' %}" class="border-indigo-500 bg-indigo-50 text-indigo-700 block border-l-4 py-2 pl-3 pr-4 text-base font-medium" aria-current="page">Volunteer</a>
        {% else %}
        	<a href="{% url 'home:volunteer' %}" class="border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium">Volunteer</a>
        {% endif %}
        {% if donate_page_active %}
        	<a href="{% url 'home:donate' %}" class="border-indigo-500 bg-indigo-50 text-indigo-700 block border-l-4 py-2 pl-3 pr-4 text-base font-medium" aria-current="page">Donate</a>
        {% else %}
        	<a href="{% url 'home:donate' %}" class="border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium">Donate</a>
        {% endif %}
        {% if q_and_a_page_active %}
        	<a href="{% url 'home:questions-and-answers' %}" class="border-indigo-500 bg-indigo-50 text-indigo-700 block border-l-4 py-2 pl-3 pr-4 text-base font-medium" aria-current="page">Q&A</a>
        {% else %}
        	<a href="{% url 'home:questions-and-answers' %}" class="border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800 block border-l-4 py-2 pl-3 pr-4 text-base font-medium">Q&A</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="py-10">
    {% block header %}
    <header>
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900">{% block header_title %}Dashboard{% endblock %}</h1>
      </div>
    </header>
    {% endblock %}
    {% block main %}
    <main>
      <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
      </div>
    </main>
    {% endblock %}
  </div>
</div>
{% endblock %}

	{% block footer %}
	<footer class="text-gray-600 text-xs my-1 mx-2 text-right">© <span x-data="{ year: new Date().getFullYear() }" x-text="year"></span> Trial Locator, Inc.</footer>
	{% endblock %}
	{% block scripts %}
	<script></script>
	{% endblock %}
	</body>
</html>